<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </head>

    <body>
        
        <div class='container'>
            <?php 
            if($datos==0 || $datos==2){
                if($datos==2) echo "<span style='color:red;'>email y/o password incorrectos. Intente nuevamente</span>";
            ?>
                <form id="formulario" method="POST">

                    <div class="form-group" >
                        <label for="correo">Email address</label>
                        <input type="email" class="form-control" id="correo" name="correo" required="true">
                    </div>
                    
                    <div class="form-group">
                        <label for="clave">Password</label>
                        <input type="password" class="form-control" id="clave" name="clave" required="true">
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Entrar</button>
                </form>
            <?php } ?>
        </div>
    </body>

</html>